services:
  - type: worker
    name: betpawa-ghost-v2
    env: python
    buildCommand: |
      export PYTHON_VERSION=3.11
      pip install --upgrade pip --no-cache-dir
      pip install --no-cache-dir -r requirements.txt
    startCommand: /usr/local/bin/python3 ghost.py
    plan: free
    envVars:
      - key: PHONE
        value: "+256 744 853640"
      - key: PYTHONUNBUFFERED
        value: "1"
